'use client'
import {useEffect,useState} from 'react'
import {useSearchParams} from 'next/navigation'
import {Suspense} from 'react'
import {Shell} from '@/components/shell'
import {Button} from '@/components/ui/button'
import {request} from '@/lib/api'
type Record={id:string;company_id:string;status:string;contact_person?:string;channel?:string;message?:string;response?:string;notes?:string;follow_up_date?:string}
function Content(){const params=useSearchParams();const [items,setItems]=useState<Record[]>([]);const [form,setForm]=useState({company_id:params.get('company')||'',status:'new',contact_person:'',channel:'',message:'',notes:''});const [error,setError]=useState('');async function load(){try{setItems(await request<Record[]>('/api/outreach'))}catch(e){setError((e as Error).message)}}useEffect(()=>{load()},[]);async function submit(){try{await request('/api/outreach',{method:'POST',body:JSON.stringify(form)});setForm({...form,message:'',notes:''});load()}catch(e){setError((e as Error).message)}}async function status(item:Record,value:string){await request(`/api/outreach/${item.id}`,{method:'PATCH',body:JSON.stringify({...item,status:value})});load()}
return <Shell><p className="text-sm font-semibold uppercase tracking-widest text-blue-600">Relationship pipeline</p><h1 className="mt-2 text-3xl font-bold">Outreach</h1><p className="mt-2 text-slate-500">Track research and conversations. No messages are sent automatically.</p><div className="mt-7 grid gap-6 lg:grid-cols-[350px_1fr]"><div className="h-fit rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-[#121b30]"><h2 className="font-semibold">Add outreach activity</h2><div className="mt-4 space-y-3">{[['company_id','Company ID'],['contact_person','Contact person'],['channel','Channel'],['message','Message'],['notes','Notes']].map(([key,label])=><label key={key} className="block text-xs text-slate-500">{label}<input value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-1 w-full rounded-lg border border-slate-200 bg-transparent px-3 py-2 text-sm dark:border-slate-700"/></label>)}<Button onClick={submit} className="w-full">Save activity</Button></div>{error&&<p className="mt-3 text-xs text-red-600">{error}</p>}</div><div className="space-y-3">{items.map(item=><div key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-[#121b30]"><div className="flex flex-wrap items-center justify-between gap-3"><a href={`/companies/${item.company_id}`} className="font-semibold text-blue-600">Company profile →</a><select value={item.status} onChange={e=>status(item,e.target.value)} className="rounded-lg border border-slate-200 bg-transparent px-3 py-2 text-sm dark:border-slate-700">{['new','researching','contacted','follow-up','responded','rejected','interested','converted'].map(x=><option key={x}>{x}</option>)}</select></div><p className="mt-3 text-sm text-slate-500">{item.contact_person||'No contact'} · {item.channel||'Channel unspecified'}</p><p className="mt-3 text-sm">{item.message||item.notes||'No notes'}</p></div>)}{!items.length&&<p className="rounded-xl border border-dashed border-slate-300 p-10 text-center text-slate-500">No outreach activity yet.</p>}</div></div></Shell>}
export default function OutreachPage(){return <Suspense><Content/></Suspense>}
