'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {Shell} from '@/components/shell'
import {Button} from '@/components/ui/button'
import {Criteria,request} from '@/lib/api'
import {Compass,ArrowRight} from 'lucide-react'
type Job={id:string;status:string;stage:string;progress:number;found?:number;inserted?:number;errors?:string[]}
export default function DiscoverPage(){const [criteria,setCriteria]=useState<Criteria>({query:'',country_code:'',industry:''});const [job,setJob]=useState<Job|null>(null);const [error,setError]=useState('');const [demo,setDemo]=useState(false)
  useEffect(()=>{request<{demo_mode:boolean}>('/api/health').then(x=>setDemo(x.demo_mode)).catch(()=>{});const id=localStorage.getItem('latest_job');if(id)request<Job>(`/api/jobs/${id}`).then(setJob).catch(()=>{})},[])
  useEffect(()=>{if(!job||job.status==='completed'||job.status==='failed')return;const timer=setInterval(()=>request<Job>(`/api/jobs/${job.id}`).then(setJob).catch(()=>{}),1500);return()=>clearInterval(timer)},[job])
  async function start(){setError('');try{const result=await request<{job_id:string}>('/api/companies/discover',{method:'POST',body:JSON.stringify(criteria)});localStorage.setItem('latest_job',result.job_id);setJob({id:result.job_id,status:'queued',stage:'Queued',progress:0})}catch(e){setError((e as Error).message)}}
  return <Shell><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-widest text-blue-600">Discovery</p><h1 className="mt-2 text-3xl font-bold">Find your next prospect</h1><p className="mt-2 text-slate-500">Search permitted company registries by name. Enriched facts appear only when a source actually supplies them.</p>{demo&&<div className="mt-7 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Demo mode is active. Browse 80 clearly labeled fictional companies. To run live discovery, configure MongoDB and set DEMO_MODE=false.</div>}<div className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-[#121b30]"><div className="flex items-center gap-2 font-semibold"><Compass size={20} className="text-blue-600"/>Target company</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm">Company name or keyword<input value={criteria.query||''} onChange={e=>setCriteria({...criteria,query:e.target.value})} placeholder="e.g. Acme" className="mt-2 w-full rounded-lg border border-slate-200 bg-transparent px-3 py-2.5 dark:border-slate-700"/></label><label className="text-sm">Country code<input value={criteria.country_code||''} onChange={e=>setCriteria({...criteria,country_code:e.target.value.toUpperCase()})} placeholder="e.g. GB, US" className="mt-2 w-full rounded-lg border border-slate-200 bg-transparent px-3 py-2.5 dark:border-slate-700"/></label></div><p className="mt-4 text-xs text-slate-500">Current free providers: GLEIF globally, Companies House for the UK with an API key. Industry and funding filters apply to stored verified records.</p><div className="mt-6 flex gap-3"><Button onClick={start} disabled={!criteria.query?.trim()||demo}>Start discovery <ArrowRight size={16}/></Button><Button asChild variant="outline"><Link href="/companies">Browse companies</Link></Button></div>{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}</div>{job&&<div className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-[#121b30]"><div className="flex items-center justify-between"><h2 className="font-semibold">{job.stage}</h2><span className="text-sm text-slate-500">{job.progress}%</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-blue-600 transition-all" style={{width:`${job.progress}%`}}/></div><div className="mt-4 flex gap-6 text-sm text-slate-500"><span>{job.found||0} found</span><span>{job.inserted||0} new</span></div>{job.errors?.map((x,i)=><p key={i} className="mt-2 text-xs text-amber-700">{x}</p>)}{job.status==='completed'&&<Link href="/companies" className="mt-5 inline-block text-sm font-semibold text-blue-600">View results →</Link>}</div>}</div></Shell>}
