'use client'
import {useCallback,useEffect,useState} from 'react'
import Link from 'next/link'
import {Shell} from '@/components/shell'
import {CompanyCard} from '@/components/company-card'
import {Button} from '@/components/ui/button'
import {Company,Criteria,request} from '@/lib/api'
import {SlidersHorizontal,X} from 'lucide-react'

type Results={items:Company[];total:number;page:number;page_size:number}
type Options={countries:string[];regions:string[];cities:string[];industries:string[];company_types:string[];funding_stages:string[];coverage:Record<string,number>}
type Job={id:string;status:string;stage:string;progress:number;found?:number;valid_candidates?:number;duplicates?:number;unique_companies?:number;enriched?:number;rejected_candidates?:number;missing_data?:Record<string,number>;provider_status?:Record<string,{status:string;candidates?:number;error?:string}>;errors?:string[]}
const blank:Criteria={countries:[],industries:[],company_types:[],sort:'prospect_score',order:'desc',page:1,page_size:20}
const industryChoices=['E-commerce','SaaS','Fintech','Healthcare','Logistics','Retail','D2C','AI/ML','EdTech']
const countryCodes='AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW'.split(' ')
const input='mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-[#10182b]'
const opportunity=['high_transaction_volume','large_customer_base','multiple_products','operational_data_heavy'] as const
const growth=['active_company','growing_headcount','multiple_growth_signals'] as const
const title=(key:string)=>key.replaceAll('_',' ').replace(/^./,x=>x.toUpperCase())
function labels(c:Criteria){return [c.countries?.length&&'Countries: '+c.countries.join(', '),c.region&&'Region: '+c.region,c.city&&'City: '+c.city,c.industries?.length&&'Industries: '+c.industries.join(', '),c.company_types?.length&&'Types: '+c.company_types.join(', '),c.employees_min!=null&&'Employees from '+c.employees_min,c.employees_max!=null&&'Employees through '+c.employees_max,c.funding_min!=null&&'Funding from $'+c.funding_min,c.funding_max!=null&&'Funding through $'+c.funding_max,c.funded_within_months&&'Funded in '+c.funded_within_months+' months',c.recently_founded_years&&'Founded in '+c.recently_founded_years+' years',c.score_min!=null&&'Prospect score '+c.score_min+'+',c.analytics_opportunity_min!=null&&'Estimated analytics '+c.analytics_opportunity_min+'+',c.query&&'Name: '+c.query].filter(Boolean) as string[]}
function matchReasons(company:Company,c:Criteria|null){if(!c)return [];const reasons:string[]=[];if(c.countries?.length&&company.location?.country_code)reasons.push('Location: '+company.location.country_code);if(c.region&&company.location?.region)reasons.push('Region: '+company.location.region);if(c.city&&company.location?.city)reasons.push('City: '+company.location.city);if(c.industries?.length&&company.industry?.length)reasons.push('Industry: '+company.industry.join(', '));if(c.employees_min!=null||c.employees_max!=null){const count=company.employees?.exact;reasons.push('Employees: '+(count!=null?count:((company.employees?.min??'?')+'–'+(company.employees?.max??'?'))))}if((c.funding_min!=null||c.funding_max!=null)&&company.funding?.total_amount_usd!=null)reasons.push('Reported funding: $'+company.funding.total_amount_usd.toLocaleString());if(c.score_min!=null&&company.prospect_score!=null)reasons.push('Prospect score: '+company.prospect_score);if(c.analytics_opportunity_min!=null)reasons.push('Estimated analytics opportunity meets selected threshold');return reasons}
export default function DiscoverPage(){
 const [draft,setDraft]=useState<Criteria>(blank),[applied,setApplied]=useState<Criteria|null>(null),[results,setResults]=useState<Results|null>(null)
 const [options,setOptions]=useState<Options>({countries:[],regions:[],cities:[],industries:[],company_types:[],funding_stages:[],coverage:{}})
 const [loading,setLoading]=useState(false),[error,setError]=useState(''),[job,setJob]=useState<Job|null>(null),[secStatus,setSecStatus]=useState('')
 const [mobile,setMobile]=useState(false),[advanced,setAdvanced]=useState(false),[saveOpen,setSaveOpen]=useState(false),[name,setName]=useState(''),[message,setMessage]=useState('')
 const search=useCallback(async(c:Criteria)=>{setLoading(true);setError('');try{const x=await request<Results>('/api/companies/search',{method:'POST',body:JSON.stringify(c)});setResults(x);setApplied(c);return true}catch(e){setError((e as Error).message);return false}finally{setLoading(false)}},[])
 useEffect(()=>{request<Options>('/api/filter-options').then(setOptions).catch(e=>setError((e as Error).message));request<{sec_enrichment_configured:boolean}>('/api/health').then(x=>setSecStatus(x.sec_enrichment_configured?'ready':'needs_contact_user_agent')).catch(()=>{});const id=new URLSearchParams(window.location.search).get('search');if(id)request<{name:string;criteria:Criteria}>('/api/searches/'+id).then(x=>{setDraft(x.criteria);setName(x.name);search(x.criteria)}).catch(e=>setError((e as Error).message))},[search])
 useEffect(()=>{if(!job||job.status==='completed'||job.status==='failed')return;const timer=setInterval(()=>request<Job>('/api/jobs/'+job.id).then(x=>{setJob(x);if(x.status==='completed'&&applied)search(applied)}).catch(()=>{}),2000);return()=>clearInterval(timer)},[job,applied,search])
 function set(key:keyof Criteria,value:unknown){setDraft(c=>({...c,[key]:value,page:1}))}
 function toggle(key:'countries'|'industries'|'company_types',value:string){setDraft(c=>{const current=c[key]||[];return {...c,[key]:current.includes(value)?current.filter(x=>x!==value):[...current,value],page:1}})}
 async function find(c=draft){setMobile(false);if(!await search(c))return;const countries=c.countries||[],industries=c.industries||[];if(countries.length>1||industries.length>1||(!c.query?.trim()&&!countries.length&&!industries.length))return;try{const x=await request<{job_id:string}>('/api/companies/discover',{method:'POST',body:JSON.stringify({...c,country_code:countries[0],industry:industries[0]})});setJob(await request<Job>('/api/jobs/'+x.job_id))}catch(e){setError((e as Error).message)}}
 async function save(){try{await request('/api/searches',{method:'POST',body:JSON.stringify({name:name.trim(),criteria:applied})});setSaveOpen(false);setMessage('Search saved.')}catch(e){setError((e as Error).message)}}
 function reset(){setDraft(blank);setJob(null);if(results)search(blank);else{setApplied(null);setResults(null)}}
 const numeric=(key:keyof Criteria,label:string)=> <label className="block text-sm">{label}<input aria-label={label} className={input} type="number" min="0" value={(draft[key] as number|undefined)??''} onChange={e=>set(key,e.target.value===''?undefined:Number(e.target.value))}/></label>
 const multi=(key:'countries'|'industries'|'company_types',values:string[],label:string,display?:(x:string)=>string)=> <div><p className="text-sm font-medium">{label}</p><div className="mt-2 max-h-36 space-y-1.5 overflow-y-auto rounded-lg border border-slate-200 p-3 dark:border-slate-700">{values.map(x=><label key={x} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={(draft[key]||[]).includes(x)} onChange={()=>toggle(key,x)}/>{display?display(x):x}</label>)}{!values.length&&<p className="text-xs text-slate-500">No sourced values available yet.</p>}</div></div>
 const check=(key:keyof Criteria,coverage:string)=> <label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!draft[key]} disabled={!options.coverage[coverage]} onChange={e=>set(key,e.target.checked)}/>{title(key)}{!options.coverage[coverage]&&<span className="text-xs text-slate-400">No verified data</span>}</label>
 const section=(name:string,body:React.ReactNode)=><section className="border-b border-slate-100 pb-5 dark:border-slate-800"><h2 className="mb-3 text-xs font-bold uppercase tracking-wider text-blue-600">{name}</h2><div className="space-y-3">{body}</div></section>
 const panel=<div className="space-y-5">{section('Where',<><p className="text-xs text-slate-500">Worldwide unless countries are selected. Choices within a field use OR.</p>{multi('countries',countryCodes,'Countries',x=>{try{return new Intl.DisplayNames(['en'],{type:'region'}).of(x)+' ('+x+')'}catch{return x}})}<div className="grid grid-cols-2 gap-3"><label className="text-sm">Region<select className={input} value={draft.region||''} onChange={e=>set('region',e.target.value||undefined)}><option value="">Any</option>{options.regions.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label className="text-sm">City<select className={input} value={draft.city||''} onChange={e=>set('city',e.target.value||undefined)}><option value="">Any</option>{options.cities.map(x=><option key={x} value={x}>{x}</option>)}</select></label></div><p className="text-xs text-slate-500">Region and city choices reflect stored records.</p></>)}
 {section('Industry',<>{multi('industries',Array.from(new Set([...industryChoices,...options.industries])),'Industries')}{multi('company_types',options.company_types,'Company types')}<p className="text-xs text-slate-500">Industry choices are search categories; company types appear when sourced records supply them.</p></>)}
 {section('Size',<div className="grid grid-cols-2 gap-3">{numeric('employees_min','Min employees')}{numeric('employees_max','Max employees')}</div>)}
 {section('Funding',<><div className="grid grid-cols-2 gap-3">{numeric('funding_min','Min total USD')}{numeric('funding_max','Max total USD')}{numeric('latest_round_min','Min latest round USD')}{numeric('latest_round_max','Max latest round USD')}</div><label className="block text-sm">Funding stage<select className={input} value={draft.funding_stage||''} onChange={e=>set('funding_stage',e.target.value||undefined)}><option value="">Any</option>{options.funding_stages.map(x=><option key={x} value={x}>{x}</option>)}</select></label></>)}
 {section('Growth signals',<><label className="block text-sm">Recently funded<select className={input} value={draft.funded_within_months||''} onChange={e=>set('funded_within_months',e.target.value?Number(e.target.value):undefined)}><option value="">Any time</option><option value="6">Past 6 months</option><option value="12">Past year</option><option value="24">Past 2 years</option></select></label><label className="block text-sm">Recently founded<select className={input} value={draft.recently_founded_years||''} onChange={e=>set('recently_founded_years',e.target.value?Number(e.target.value):undefined)}><option value="">Any time</option><option value="3">Past 3 years</option><option value="5">Past 5 years</option><option value="10">Past 10 years</option></select></label>{growth.map(x=>check(x,x==='active_company'?'company_status':'signals.'+x))}</>)}
 {section('Data / analytics opportunity',<><p className="text-xs text-slate-500">Analytics score is an industry-based estimate.</p><label className="block text-sm">Estimated analytics opportunity<select className={input} value={draft.analytics_opportunity_min||''} onChange={e=>set('analytics_opportunity_min',e.target.value?Number(e.target.value):undefined)}><option value="">Any</option><option value="7">High (7+/10)</option><option value="9">Very high (9+/10)</option></select></label>{opportunity.map(x=>check(x,'opportunity_evidence.'+x))}</>)}
 {section('Prospect quality',<div className="grid grid-cols-2 gap-3">{numeric('score_min','Min prospect score')}{numeric('growth_score_min','Min growth score')}</div>)}
 <button type="button" className="text-sm font-semibold text-blue-600" onClick={()=>setAdvanced(!advanced)}>{advanced?'Hide':'Show'} advanced filters</button>
 {advanced&&section('Advanced',<><label className="block text-sm">Company name<input className={input} value={draft.query||''} onChange={e=>set('query',e.target.value)}/></label><div className="grid grid-cols-2 gap-3">{numeric('founded_min','Founded from')}{numeric('founded_max','Founded through')}</div></>)}
 <div className="flex gap-2"><Button onClick={()=>find()} disabled={loading} className="flex-1">{loading?'Finding…':'Find Companies'}</Button><Button variant="outline" onClick={reset}>Clear</Button></div></div>
 return <Shell><div className="mb-7"><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Discovery workspace</p><h1 className="mt-1 text-3xl font-bold">DISCOVER COMPANIES</h1><p className="mt-2 text-slate-500">Tell ScoutBase what kind of company you are looking for, and it will find sourced matches.</p>{secStatus==='needs_contact_user_agent'&&<p className="mt-3 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-800">SEC enrichment is unavailable until SEC_USER_AGENT includes a real contact address. GLEIF, Wikidata, and applicable GitHub enrichment can still run.</p>}</div>
 <div className="grid items-start gap-6 lg:grid-cols-[340px_minmax(0,1fr)]"><aside className="hidden rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-[#121b30] lg:block"><div className="mb-5 flex items-center gap-2 font-semibold"><SlidersHorizontal size={17}/> Filters</div>{panel}</aside><main className="min-w-0">
 <button className="mb-4 flex w-full items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white p-3 text-sm font-semibold dark:border-slate-700 dark:bg-[#121b30] lg:hidden" onClick={()=>setMobile(true)}><SlidersHorizontal size={16}/> Filters and Find Companies</button>
 <div className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-[#121b30]"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{results?results.total.toLocaleString()+' matching companies':'Companies matching your filters'}</h2><p className="mt-1 text-sm text-slate-500">{results?'Count from the current database. Filter groups use AND.':'Choose filters, then select Find Companies.'}</p></div>{results&&<Button variant="outline" size="sm" onClick={()=>setSaveOpen(true)}>Save search</Button>}</div>{applied&&<div className="mt-4 flex flex-wrap items-center gap-2">{labels(applied).map(x=><span key={x} className="rounded-full bg-blue-50 px-2.5 py-1 text-xs text-blue-700 dark:bg-blue-950">{x}</span>)}{!labels(applied).length&&<span className="text-xs text-slate-500">Worldwide · all industries</span>}<button className="text-xs font-semibold text-blue-600" onClick={reset}>Clear all</button></div>}
 {results&&<div className="mt-4 flex items-center gap-3 border-t border-slate-100 pt-4 text-sm dark:border-slate-800"><label>Sort by <select className="ml-2 rounded-lg border border-slate-200 bg-transparent p-1.5 dark:border-slate-700" value={applied?.sort||'prospect_score'} onChange={e=>{const c={...applied,sort:e.target.value,page:1};setDraft(c);search(c)}}><option value="prospect_score">Prospect score</option><option value="funding.total_amount_usd">Funding</option><option value="employees.min">Employees</option><option value="founded_year">Founded year</option><option value="signals.growth_score">Growth score</option></select></label><button className="text-blue-600" onClick={()=>{const c={...applied,order:applied?.order==='asc'?'desc':'asc',page:1};setDraft(c);search(c)}}>{applied?.order==='asc'?'Ascending ↑':'Descending ↓'}</button></div>}</div>
 {error&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message&&<p className="mt-4 text-sm text-emerald-700">{message} <Link className="underline" href="/searches">View saved searches</Link></p>}
 {applied&&!job&&<p className="mt-3 text-xs text-slate-500">Results reflect sourced records in MongoDB. Current external discovery supports a single country, a single industry, or a company name. Size, funding, growth, and opportunity filters narrow records only when those fields are sourced.</p>}{job&&<div className="mt-4 rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm dark:border-blue-900 dark:bg-blue-950"><p className="font-semibold">Live discovery: {job.stage} ({job.progress}%)</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1"><span>Raw candidates: {job.found??0}</span><span>Valid: {job.valid_candidates??0}</span><span>Duplicates: {job.duplicates??0}</span><span>Unique: {job.unique_companies??0}</span><span>Enriched: {job.enriched??0}</span><span>Rejected: {job.rejected_candidates??0}</span></div>{job.missing_data&&<p className="mt-2">Missing data: {Object.entries(job.missing_data).map(([key,value])=>key+' '+value).join(' · ')}</p>}{job.provider_status&&<p className="mt-2">Provider coverage: {Object.entries(job.provider_status).map(([key,value])=>key+' '+value.status+(value.candidates!=null?' ('+value.candidates+')':'')).join(' · ')}</p>}{job.errors?.map((x,i)=><p key={i} className="mt-1 text-amber-700">Provider issue: {x}</p>)}</div>}
 <div className="mt-5 space-y-4">{results?.items.map(c=><CompanyCard key={c.id} company={c} showReasons matchReasons={matchReasons(c,applied)}/>)}{results&&results.total===0&&<div className="rounded-2xl border border-dashed border-slate-300 p-8 text-center dark:border-slate-700"><h3 className="font-semibold">No companies match these filters</h3><p className="mt-2 text-sm text-slate-500">Try a broader size or funding range, or fewer location and industry choices. Unknown fields do not count as matches.</p>{(applied?.employees_min!=null||applied?.employees_max!=null||applied?.funding_min!=null||applied?.funding_max!=null||applied?.score_min!=null)&&<Button className="mt-4 mr-2" variant="outline" onClick={()=>{const c={...applied,employees_min:undefined,employees_max:undefined,funding_min:undefined,funding_max:undefined,score_min:undefined};setDraft(c);search(c)}}>Relax ranges</Button>}{!!applied?.countries?.length&&<Button className="mt-4 mr-2" variant="outline" onClick={()=>{const c={...applied,countries:[]};setDraft(c);search(c)}}>Search worldwide</Button>}{!!applied?.industries?.length&&<Button className="mt-4" variant="outline" onClick={()=>{const c={...applied,industries:[]};setDraft(c);search(c)}}>Include all industries</Button>}</div>}{results&&results.total>results.page*results.page_size&&<Button variant="outline" onClick={()=>{const c={...applied,page:(applied?.page||1)+1};setDraft(c);search(c)}}>Next page</Button>}{results&&(applied?.page||1)>1&&<Button variant="outline" onClick={()=>{const c={...applied,page:Math.max(1,(applied?.page||1)-1)};setDraft(c);search(c)}}>Previous page</Button>}</div></main></div>
 {mobile&&<div className="fixed inset-0 z-50 bg-slate-950/50 lg:hidden" onClick={()=>setMobile(false)}><div role="dialog" aria-modal="true" aria-label="Company filters" className="ml-auto h-full w-full max-w-md overflow-y-auto bg-white p-5 dark:bg-[#121b30]" onClick={e=>e.stopPropagation()}><div className="mb-5 flex justify-between"><strong>Filters</strong><button aria-label="Close filters" onClick={()=>setMobile(false)}><X/></button></div>{panel}</div></div>}
 {saveOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" onClick={()=>setSaveOpen(false)}><div role="dialog" aria-modal="true" aria-label="Save search" className="w-full max-w-md rounded-2xl bg-white p-6 dark:bg-[#121b30]" onClick={e=>e.stopPropagation()}><h2 className="font-semibold">Save these filters</h2><p className="mt-1 text-sm text-slate-500">Rerun this exact criteria set later.</p><input autoFocus aria-label="Search name" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. European fintech prospects" className={input}/><div className="mt-5 flex gap-2"><Button onClick={save} disabled={!name.trim()}>Save search</Button><Button variant="outline" onClick={()=>setSaveOpen(false)}>Cancel</Button></div></div></div>}</Shell>
}
