'use client'
import {useEffect,useState} from 'react'
import {Shell} from '@/components/shell'
import {CompanyCard} from '@/components/company-card'
import {Button} from '@/components/ui/button'
import {Company,request} from '@/lib/api'
type Saved={id:string;company_id:string;tags:string[];notes:string;priority:string;status:string}
export default function SavedPage(){const [items,setItems]=useState<Saved[]>([]);const [companies,setCompanies]=useState<Record<string,Company>>({});const [error,setError]=useState('');async function load(){try{const list=await request<Saved[]>('/api/saved-companies');setItems(list);const pairs=await Promise.all(list.map(async x=>[x.company_id,await request<Company>(`/api/companies/${x.company_id}`)] as const));setCompanies(Object.fromEntries(pairs))}catch(e){setError((e as Error).message)}}useEffect(()=>{load()},[]);async function remove(id:string){await request(`/api/saved-companies/${id}`,{method:'DELETE'});load()}async function edit(item:Saved,changes:Partial<Saved>){await request('/api/saved-companies',{method:'POST',body:JSON.stringify({...item,...changes})});load()}
return <Shell><p className="text-sm font-semibold uppercase tracking-widest text-blue-600">Your shortlist</p><h1 className="mt-2 text-3xl font-bold">Saved companies</h1><p className="mt-2 text-slate-500">Research, tag and prioritize prospects before outreach.</p>{error&&<p className="mt-5 text-red-600">{error}</p>}<div className="mt-7 space-y-4">{items.map(item=>companies[item.company_id]&&<div key={item.id}><CompanyCard company={companies[item.company_id]}/><div className="flex flex-wrap items-center gap-3 rounded-b-xl border border-t-0 border-slate-200 bg-white px-5 py-3 text-sm dark:border-slate-800 dark:bg-[#121b30]"><select aria-label="Priority" value={item.priority} onChange={e=>edit(item,{priority:e.target.value})} className="rounded-lg border border-slate-200 bg-transparent p-2 dark:border-slate-700"><option value="low">Low priority</option><option value="medium">Medium priority</option><option value="high">High priority</option></select><select aria-label="Status" value={item.status} onChange={e=>edit(item,{status:e.target.value})} className="rounded-lg border border-slate-200 bg-transparent p-2 dark:border-slate-700">{['new','researching','contacted','follow-up','responded','rejected','interested','converted'].map(x=><option key={x}>{x}</option>)}</select><input aria-label="Notes" defaultValue={item.notes} onBlur={e=>edit(item,{notes:e.target.value})} placeholder="Notes" className="min-w-40 flex-1 rounded-lg border border-slate-200 bg-transparent p-2 dark:border-slate-700"/><Button variant="ghost" size="sm" onClick={()=>remove(item.company_id)}>Remove</Button></div></div>)}{!items.length&&<p className="rounded-xl border border-dashed border-slate-300 p-10 text-center text-slate-500">No saved companies yet. Save a prospect from the company library.</p>}</div></Shell>}
